---
version: '3.4'
services:
    redis1:
        image: redis:5.0-alpine
        command:
        - redis-server
        - '--appendonly'
        - 'no'
    postgres:
        image: postgres:9.6-alpine
        environment:
            POSTGRES_PASSWORD: "password"
            POSTGRES_DB: "hashes"
            POSTGRES_HOST_AUTH_METHOD: "trust"
    hashes:
        depends_on:
            - postgres
            - redis1
        environment:
            REDIS_HOST: 'redis1'
            POSTGRES_HOST: 'postgres'
        build: .
        